- hosts: slave
  tasks:

  - name: Copy jdk package
    copy: 
       src: /root/jdk-8u171-linux-x64.rpm 
       dest: /root/jdk-8u171-linux-x64.rpm

  - name: Copy hadoop package 
    copy:
       src: /root/hadoop-1.2.1-1.x86_64.rpm 
       dest: /root/hadoop-1.2.1-1.x86_64.rpm


  - name: Installing jdk package
    command: rpm -ivh /root/jdk-8u171-linux-x64.rpm --force


  - name: Installing hadoop

    command: rpm -iv /root/hadoop-1.2.1-1.x86_64.rpm --force

  - file:  
      state: directory 
      path: /dn

  - name: Copy hdfs-site.xml file
    copy: 
      src: /root/slave_files/hdfs-site.xml
      dest: /etc/hadoop/

  - name: Copy core-site.xml file
    copy: 
      src: /root/slave_files/core-site.xml
      dest: /etc/hadoop/

  - name: Startting Slave Node 
    command: hadoop-daemon.sh start datanode  
